### ISSUE TITLE
Issue upgrading ruby-mini_portile2.

### ISSUE THREAD

**Issue by Zerophase** [anatol/quarry#103]
I'm pretty sure this is related to a conflict between quarry and the Arch repos; since, the arch package for ruby-mini_portile2 has not been upgraded in almost a year. Arch repo has version 2.3.0-3, and the version attempted to be installed is ruby-mini_portile2-2.3-2.3.0-1. This is almost definitely related to a change in nokogiri.

Error messages:

`
error: failed to commit transaction (conflicting files)
ruby-mini_portile2-2.3: /usr/lib/ruby/gems/2.5.0/gems/mini_portile2-2.3.0/lib/mini_portile2.rb exists in filesystem (owned by ruby-mini_portile2)
ruby-mini_portile2-2.3: /usr/lib/ruby/gems/2.5.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb exists in filesystem (owned by ruby-mini_portile2)
ruby-mini_portile2-2.3: /usr/lib/ruby/gems/2.5.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile_cmake.rb exists in filesystem (owned by ruby-mini_portile2)
ruby-mini_portile2-2.3: /usr/lib/ruby/gems/2.5.0/gems/mini_portile2-2.3.0/lib/mini_portile2/version.rb exists in filesystem (owned by ruby-mini_portile2)
ruby-mini_portile2-2.3: /usr/lib/ruby/gems/2.5.0/specifications/mini_portile2-2.3.0.gemspec exists in filesystem (owned by ruby-mini_portile2)
`

**Comment by anatol** [comment]
It is indeed a problem with Arch version of the package. I bumped `ruby-mini_portile2` and now it should be good.

**Comment by anatol** [comment]
Should be fixed now in Arch.
