### ISSUE TITLE
gollum fails to start, because not recognizing unf 0.2.0.beta2

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#115]
```
$ /usr/bin/gollum 
Traceback (most recent call last):
	16: from /usr/bin/gollum:23:in `<main>'
	15: from /usr/lib/ruby/2.7.0/rubygems.rb:295:in `activate_bin_path'
	14: from /usr/lib/ruby/2.7.0/rubygems.rb:295:in `synchronize'
	13: from /usr/lib/ruby/2.7.0/rubygems.rb:296:in `block in activate_bin_path'
	12: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1373:in `activate'
	11: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	10: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `each'
	 9: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	 8: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1373:in `activate'
	 7: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 6: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `each'
	 5: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	 4: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1373:in `activate'
	 3: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 2: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `each'
	 1: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1402:in `block in activate_dependencies'
/usr/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'unf' (~> 0.1.0) - did find: [unf-0.2.0.beta2] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/erich/.gem/ruby/2.7.0:/usr/lib/ruby/gems/2.7.0', execute `gem env` for more information
```
This is with
```
$ pacman -Q ruby-gollum ruby-unf
ruby-gollum 4.1.4-4
ruby-unf 0.2.0.beta2-3
```
I believe, this happens since the update of unf from 0.1.4-7 to 0.2.0.beta2-3
see also [the bug filed against ruby-unf](https://bugs.archlinux.org/task/65283)
Is this something that needs to be fixed on the packaging level (advertisement / detection of versions) or is this something which needs to be fixed in gollum?

**Comment by deep-42-thought** [comment]
Considering the discussion in the arch bug tracker, a working solution (for me) to defuse the issue would be to introduce a `ruby-unf` package in quarry (or a `ruby-unf-stable` package which provides `ruby-unf=0.1.4`) which packages the latest stable version of unf. Then I (and everyone who wants to use it) simply needs to chose that package over the one provided by archlinux - e.g. by putting `[quarry]` in front of other repositories in the `pacman.conf` (works in both cases) or by choosing the right package (works only in the `ruby-unf-stable` case).
What do you think of that solution, @anatol ?

**Comment by anatol** [comment]
For now the best way to workaround this problem is to get to the stable version of `unf` gem. Please download it from here https://pkgbuild.com/~anatolik/ruby-unf/

 I will continue on getting ruby packages in `[community]` back on track.

**Comment by deep-42-thought** [comment]
Thanks for looking into this :-) (and sorry for the fight which I kicked off on the other bug tracker :-/ )
I have downgraded my ruby-unf and put it into the IgnorePkg list. Is the package which you linked above identical to the old one (besides the `epoch`)?

**Comment by anatol** [comment]
A workaround for `ruby-twitter` to depend on any `ruby-unf` instead of `ruby-unf ~> 0.1.0` has been added to quarry. The `ruby-unf-beta` hack above is not needed anymore.
