### ISSUE TITLE
no recent update

### ISSUE THREAD

**Issue by gagalago** [anatol/quarry#128]
it seems that there is no recent update?
How can we help you to solve this issue?

https://pkgbuild.com/~anatolik/quarry/ says that the last update was at 12-Feb-2022 20:32 so around 6 months ago.

**Comment by anatol** [comment]
Sorry for this long delay.

There were several issues with the official repo. Some of the packages are way out-of-date and it confused quarry generator. I was hoping that the official package bumped but it did not happen, unfortunately. So I added a workaround to quarry itself and updated the packages.

Quarry is up-to-date now. Please try it and let me know if you see any issues.
