### ISSUE TITLE
wikitext

### ISSUE THREAD

**Issue by Kendos-Kenlen** [anatol/quarry#27]
Hi,

Could it be possible to add the "wikitext" gem (https://rubygems.org/gems/wikitext) ?

It's a native extension, so it need root rights to be build. An installation with pacman could be better than installing the gem system-wide.

**Comment by anatol** [comment]
Tried to build the gem and it says "extconf.rb:32:in `<main>': unsupported Ruby version: 2.2.2 (RuntimeError)". The gem is not compatible with current ruby version at Arch. https://github.com/wincent/wikitext/blob/master/ext/wikitext/extconf.rb


Please contact upstream to resolve the issue. Thanks.

**Comment by Kendos-Kenlen** [comment]
Hi,

It is done, I'll let you know when the concern is resolved.
Sorry for the bad request.

**Comment by Kendos-Kenlen** [comment]
Problem solved

**Comment by anatol** [comment]
The gem posted at rubygems.org is broken

```
$ ~/.gem/ruby/2.2.0/bin/wikitext 
/home/anatol/.gem/ruby/2.2.0/gems/wikitext-4.1.1/Gemfile not found
```

Posted problem here https://github.com/wincent/wikitext/commit/32b7c915c2f66cd2dbfcd7c41516a764e407045e

**Comment by anatol** [comment]
Implemented. wikitext is now managed by quarry.
