### ISSUE TITLE
pacman -Syu gave conflicts today

### ISSUE THREAD

**Issue by rubdos** [anatol/quarry#33]
Apparently, the default `ruby` package in Arch provides with some files that are also present in some packages here:

> error: failed to commit transaction (conflicting files)
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/hoe/minitest.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/assertions.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/autorun.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/benchmark.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/expectations.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/hell.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/mock.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/parallel.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/pride.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/pride_plugin.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/spec.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/test.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/lib/minitest/unit.rb exists in filesystem
> ruby-minitest: /usr/lib/ruby/gems/2.3.0/specifications/minitest-5.8.3.gemspec exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/alt_system.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/backtrace.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/clean.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/cloneable.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/contrib/compositepublisher.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/contrib/ftptools.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/contrib/publisher.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/contrib/rubyforgepublisher.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/contrib/sshpublisher.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/contrib/sys.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/cpu_counter.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/default_loader.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/dsl_definition.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/early_time.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/ext/core.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/ext/module.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/ext/pathname.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/ext/string.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/ext/time.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_creation_task.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_list.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_task.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_utils.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/gempackagetask.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/invocation_chain.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/invocation_exception_mixin.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/late_time.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/linked_list.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/loaders/makefile.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/multi_task.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/name_space.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/packagetask.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/pathmap.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/phony.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/private_reader.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/promise.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/pseudo_status.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/rake_module.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/rdoctask.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/ruby182_test_unit_fix.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/rule_recursion_overflow_error.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/runtest.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/scope.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task_argument_error.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task_arguments.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task_manager.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/tasklib.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/testtask.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/thread_history_display.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/thread_pool.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/trace_output.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/version.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/win32.rb exists in filesystem
> ruby-rake: /usr/lib/ruby/gems/2.3.0/specifications/rake-10.4.2.gemspec exists in filesystem
> ruby-net-telnet: /usr/lib/ruby/gems/2.3.0/gems/net-telnet-0.1.1/lib/net-telnet.rb exists in filesystem
> ruby-net-telnet: /usr/lib/ruby/gems/2.3.0/gems/net-telnet-0.1.1/lib/net/telnet.rb exists in filesystem
> ruby-net-telnet: /usr/lib/ruby/gems/2.3.0/gems/net-telnet-0.1.1/lib/net/telnet/version.rb exists in filesystem
> ruby-net-telnet: /usr/lib/ruby/gems/2.3.0/specifications/net-telnet-0.1.1.gemspec exists in filesystem

I ran `pacman -Syu --ignore ruby-net-telnet,ruby-rake,ruby-minitest` to overcome this for now.

**Comment by anatol** [comment]
Ruby package provides these gems. Just delete these conflicting gems from quarry `pacman -Rdd ruby-rake ruby-minitest`

**Comment by rubdos** [comment]
I did it with dependency check. `ruby-rake` and `ruby-minitest` weren't a problem, but `ruby-net-telnet` was. I had to delete some more things (I don't use them, so no problem atm).

Just so you know that `ruby-chef`-stuff depends indirectly on `ruby-net-telnet`

I removed
> Packages (7) ruby-chef-12.6.0-2  ruby-chef-server-10.30.4-3
>              ruby-chef-server-webui-10.30.4-5  ruby-chefspec-4.5.0-2
>              ruby-net-telnet-0.1.1-1  ruby-serverspec-2.27.0-1
>              ruby-specinfra-2.47.1-1

because

> :: ruby-chef-server: requires ruby-chef-server-webui
> :: ruby-chef-server-webui: requires ruby-chef
> :: ruby-chefspec: requires ruby-chef
> :: ruby-chef: requires ruby-specinfra
> :: ruby-serverspec: requires ruby-specinfra
> :: ruby-specinfra: requires ruby-net-telnet

**Comment by anatol** [comment]
Thanks for the report. The problem has been fixed. Run `pacman -Rdd ruby-net-telnet` then update your system.

**Comment by rubdos** [comment]
Thank you :)
