### ISSUE TITLE
Octopress package incomplete

### ISSUE THREAD

**Issue by runical** [anatol/quarry#42]
Sorry to bother you with octopress again, however, the package provided is missing some of the files needed to make the package fully functional.

The package generated by quarry has a bin and lib directory in $pkgdir/lib/ruby/gems/2.3.0/gems/octopress-3.0.11. However, when installing via gem, it also comes with a few more files and directories in that directory, most notably the scaffold directory without which octopress cannot init a new blog.

Unfortunately, I have no clue why this is happening (the pkgbuild in quarry.rb seems OK).

**Comment by anatol** [comment]
Thanks for reporting it. It means a config file with `include` option should be added (like this one https://github.com/anatol/quarry/blob/master/config.pkg/fpm.yaml). I'll make the changes.

What is the best octopress example that I can use for testing its functionality?

**Comment by runical** [comment]
Ah, that makes sense. As for testing, I'd say that you'd best try at least to initialise a new blog with `octopress init`. After that, testing the `octopress docs` command and `jekyll build` should suffice from my quick look as `deploy` is handeled by another gem and the other commands only really move files around from what I can tell.

My guess is that at the very least the "scaffold" (for `init`), "local" (for `docs`) and "site" (for `jekyll build`) directories are needed.

**Comment by anatol** [comment]
I added these directories and when I run `octopress docs` I get following error

```
$ octopress docs
  Liquid Exception: no implicit conversion of nil into String in index.html
```

That seems the same as https://github.com/octopress/octopress/issues/158
