### ISSUE TITLE
Add t

### ISSUE THREAD

**Issue by moviuro** [anatol/quarry#43]
Hi @anatol ,

Thanks for the repo!
I'm not sure if this is the place to ask, but could you add https://github.com/sferik/t to the quarry repo?

Also, if you need a mirror for the repo, ask away, I have a server doing nothing that could help.

**Comment by anatol** [comment]
Just added the gem. Enjoy.

PS The project name is a bit weird.

**Comment by moviuro** [comment]
thanks @anatol , you rock :wink:
