### ISSUE TITLE
ruby-mail pulls older version

### ISSUE THREAD

**Issue by Zerophase** [anatol/quarry#46]
When pulling the latest version of rails the previous versions mail gem keeps getting pulled down. I tried uninstalling rails, and just pulling `ruby-mail-2.6.4`, and keep getting version `2.6.3`. Is this a bug or do I need to enter another command on top of `pacman -S ruby-mail` to get the latest version?

**Comment by anatol** [comment]
That is becuase `2.6.3` comes from `[community]` arch repository. The official repo goes first in your `pacman.conf` and that is why it is installed instead of the quarry one.

I am going to update the [community] package to the latest version.

**Comment by Zerophase** [comment]
Just moved quarry to the top of the list.

**Comment by anatol** [comment]
It might not be the best idea. It is better to keep `[community]` packages up to date.

**Comment by Zerophase** [comment]
Yeah, I didn't think it would be ideal. Is there a command for pacman that would pull from quarry, for Ruby updates instead?

Something, like --aur.
