### ISSUE TITLE
jquery-rails can't find jquery.

### ISSUE THREAD

**Issue by Zerophase** [anatol/quarry#62]
jquery-rails needs the `vendor/assets/javascripts` path to find jquery as intended. I can always just soft link the folder used by jquery on the aur, but rails includes each major version of jquery with the gem.  If you're fine with including the vendor folder I'll just submit a pull request.

I'm guessing it would be
```yaml
include:
  - vendor/assets/javascripts/*
```

**Comment by anatol** [comment]
Yes, it sounds reasonable. Please send a PR. You don't need `/*` part in the `include` though.
