### ISSUE TITLE
Cannot find rake for project

### ISSUE THREAD

**Issue by Zerophase** [anatol/quarry#65]
I'm having issues getting the correct `rake` for my project with these lines in the Rakefile:
```ruby
#!/usr/bin/env rake

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task default: :spec
```

I believe it's caused by rake not having 'exe/rake`

The error message I receive is: 
```
Error:[rake --tasks] /usr/bin/rake:22:in `load': cannot load such file -- /usr/lib/ruby/gems/2.3.0/specifications/exe/rake (LoadError)
	from /usr/bin/rake:22:in `<main>'
```
`usr/bin/rake` line 22 has:
```ruby
load Gem.bin_path('rake', 'rake', version)
``` 

Here's the reset of the rake gem files that aren't included incase any other files or directories should be added for rake.
```
.
├── appveyor.yml
├── bin
│   ├── console
│   └── setup
├── CONTRIBUTING.rdoc
├── doc
│   ├── command_line_usage.rdoc
│   ├── example
│   │   ├── a.c
│   │   ├── b.c
│   │   ├── main.c
│   │   ├── Rakefile1
│   │   └── Rakefile2
│   ├── glossary.rdoc
│   ├── jamis.rb
│   ├── proto_rake.rdoc
│   ├── rake.1
│   ├── rakefile.rdoc
│   └── rational.rdoc
├── exe
│   └── rake
├── Gemfile
├── Rakefile
├── rake.gemspec
└── README.rdoc
```

**Comment by anatol** [comment]
It is weird that the app tries to load files from `specifications` directory. That dir contains gem spec files only.

Also I suggest avoid installing `rake` from `quarry` unless there is real need in doing this. `rake` gem is also installed via `ruby` Arch package and it might clash with `quarry` version.

**Comment by anatol** [comment]
FYI: `rake` has been decoupled from `ruby` package. You can install update `ruby-rake` package separately from `ruby`.

**Comment by eli-schwartz** [comment]
Is this obsoleted by #83 and #74?

**Comment by anatol** [comment]
If the issue still exist then it should be filed against `[community]` `ruby-rake` package.
