### ISSUE TITLE
gems included with ruby and quarry.

### ISSUE THREAD

**Issue by Zerophase** [anatol/quarry#67]
I just wanted to let you know rake and minitest are included with ruby 2.4. Should those gems be removed from this repo?

**Comment by anatol** [comment]
Yes it is a known fact. But I still would like to keep these gems just in case someone wants to install version that differs from the Ruby default.

I am going to close it as Wai unless it causes some problems for you.

**Comment by Zerophase** [comment]
I just had to remove the packages. Did the last release of Ruby include these gems as well?

**Comment by anatol** [comment]
It is related to https://bugs.archlinux.org/task/38411

At the moment of new ruby release (like now with ruby 2.4) its distribution contains the latest `rake` `rdoc` `test-unit`... gems. And it conflicts with one produced by quarry. But over time maintainers of these gems release new versions. Quarry keeps creating packages for it so users can install if needed - at this moment it will not conflict with ruby package anymore ... unit the next ruby release.

It is a bit weird situation that ruby includes libraries that are also distributed and updated as gems. It creates confusion.

**Comment by Zerophase** [comment]
Yeah, it does create confusion. It's one thing if those gems are needed for Ruby to install. But, it just seems like it would make more sense for those gems to be installed separately during the Ruby install process.
