### ISSUE TITLE
provide rsync for mirroring

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#78]
Is it possible to provide access via rsync for mirroring the repository?
If not, is it possible to create a `lastupdate` file?

**Comment by anatol** [comment]
I am not sure if it easy to enable rsync for pkgbuild.com user repos.

Thus I added `lastupdate` file to the it repo. The file is located here https://pkgbuild.com/~anatolik/quarry/  please take a look and let me know if it works for you.

**Comment by deep-42-thought** [comment]
Thanks, works like a charm.

**Comment by anatol** [comment]
I am not familiar with mirroring rules so maybe you can help me to clarify it. What is required location for `lastupdate` file? Could it be located in the same directory as repo index `*.db` file i.e. here https://pkgbuild.com/~anatolik/quarry/x86_64/

**Comment by deep-42-thought** [comment]
AFAIK there are no rules.
However, usually it's at the topmost directory that makes sense, e.g. https://pkgbuild.com/~anatolik if you only host quarry (or the `lastupdate` file is meant for all subdirectories) or https://pkgbuild.com/~anatolik/quarry if you host anything else in the former directory.
