### ISSUE TITLE
duplicates of upstream ruby-packages

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#83]
Hi,

I just noticed, that there is `ruby-rdoc` in extra and in quarry. I wonder:
a) if this is necessary and
b) which version of both I should install - currently I have listed quarry last, because I don't like the idea of overwriting official packages by packages from foreign, unofficial repositories, but I guess that's wrong then.

cheers, deep-42-thought

**Comment by anatol** [comment]
Indeed currently `quarry` builds gems including those that are already present in standard repos. It is a quarry issue and eventually should be fixed.

>  I have listed quarry last

That is right decision. Use packages from `[community]` first.

**Comment by eli-schwartz** [comment]
I should probably take another stab at #74

**Comment by anatol** [comment]
Yeah, that is one of the main tasks in quarry now.

It somewhat related to #84 - enhance quarry to maintain `[community]` Arch repository.

**Comment by anatol** [comment]
Eli's pull request #74 fixed this issue. Now quarry does not duplicated `[community]` ruby packages.
